---
- name: Hello World Playbook
  hosts: all
  gather_facts: no

  tasks:
    - debug: msg="Hello World I am a new commit!"
    - name: Ensure Httpd Is Installed
      become: yes
      ansible.builtin.copy:
          content: "file edited by {{NAME}}"
          dest: /etc/motd 
          mode: 0666
